### ISSUE TITLE
Deliver an integrated program to illustrate SDL-oriented system calls

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#101]
In order to illustrate how to use [SDL-oriented system calls](https://github.com/sysprog21/rv32emu/blob/master/docs/syscall.md), we can deliver an integrated program  which utilizes SDL window system and input events. [smolnes](https://github.com/binji/smolnes) is ideal for its small footprint and powerful features -- a NES emulator less than 500 lines of code (`deobfuscated.c`). We can redistribute the open source NES ROM files such as [falling-nes](https://github.com/xram64/falling-nes).

Expected output:
1. Replace SDL functions in [smolnes](https://github.com/binji/smolnes) with rv32emu specific SDL oriented system calls.
2. Verify the functionality of NES emulation with [falling-nes](https://github.com/xram64/falling-nes) and some NES games.
3. By default, the emulator looks for `rom.nes` and fallbacks to use `falling.nes` if the former is not found.
4. Add some preliminary documentation on the usage of SDL-oriented system calls in the source code of modified [smolnes](https://github.com/binji/smolnes).

Later, we might initiate the binary translator which converts 6502 opcode into RV32 or specific IR when we proceed #81, meaning that the NES emulation can be quite efficient.

**Comment by jserv** [comment]
Besides a functioned NES emulator, we can still provide a standalone renderer (or tiny game engine) to present the ability of SDL oriented system call. @alanjian85, do you have something in mind?

**Comment by alanjian85** [comment]
> Besides a functioned NES emulator, we can still provide a standalone renderer (or tiny game engine) to present the ability of SDL oriented system call. @alanjian85, do you have something in mind?

I have previously satisfied all the four requirements listed above. However, I'm hesitating whether to create a static binary translator that converts a 6502 ROM file to a RISC-V executable file, eliminating the necessity of using smolnes; or a JIT compiler in smolnes; or even optimize rv32emu itself. Furthermore, the lack of memory mapping and translation in rv32emu places limitations on optimization techniques, making some of them infeasible.

**Comment by jserv** [comment]
Thank @alanjian85 again for the great work!

Later, we might consider enhancing smolnes using the [cached interpreter](https://emudev.org/2021/01/31/cached-interpreter.html) technique, which would avoid unnecessary instruction decoding efforts and reduce instruction dispatch overhead.
