### ISSUE TITLE
Improve memory read/write

### ISSUE THREAD

**Issue by qwe661234** [sysprog21/rv32emu#122]
After analyzing the data collected during the execution of the dhrystone benchmark, it becomes evident that the primary performance bottleneck lies in memory read and write operations. To address this issue and improve performance, we should consider modifying the implementation of these memory operations.

```
  21.15%  rv32emu  rv32emu           [.] memory_write
  17.21%  rv32emu  rv32emu           [.] do_sw
  12.82%  rv32emu  rv32emu           [.] do_lw
   6.89%  rv32emu  rv32emu           [.] memory_read_w
   6.68%  rv32emu  rv32emu           [.] on_mem_write_w

```

**Comment by jserv** [comment]
[semu.c](https://github.com/jserv/semu/blob/master/semu.c) applies the technique [Duff's device](https://en.wikipedia.org/wiki/Duff%27s_device) to generalize memory operations. See `ram_load` and `ram_store`.
We may eliminate unnecessary range checks for memory chunks. Furthermore, memory chunk in `src/io.c` is not really vital for implementing RV32 emulation though.
