### ISSUE TITLE
Security: Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#137]
Reported by CodeQL.

src/main.c:183
```c
    /* open the ELF file from the file system */
    elf_t *elf = elf_new();
    if (!elf_open(elf, opt_prog_name)) {
```

This argument to a file access function is derived from  and then passed to `elf_open(path)`, which calls `open(__path)`.

Accessing paths controlled by users can allow an attacker to access unexpected resources. This can result in sensitive information being revealed or deleted, or an attacker being able to influence behavior by modifying unexpected files.

Paths that are naively constructed from data controlled by a user may contain unexpected special characters, such as "..". Such a path may potentially point to any directory on the filesystem.

Recommendation
Validate user input before using it to construct a filepath. Ideally, follow these rules:
* Do not allow more than a single "." character.
* Do not allow directory separators such as "/" or "\" (depending on the filesystem).
* Do not rely on simply replacing problematic sequences such as "../". For example, after applying this filter to ".../...//" the resulting string would still be "../".
* Ideally use a whitelist of known good patterns.

References
- OWASP: [Path Traversal](https://owasp.org/www-community/attacks/Path_Traversal).
- Common Weakness Enumeration: [CWE-22](https://cwe.mitre.org/data/definitions/22.html).
- Common Weakness Enumeration: [CWE-23](https://cwe.mitre.org/data/definitions/23.html).
- Common Weakness Enumeration: [CWE-36](https://cwe.mitre.org/data/definitions/36.html).
- Common Weakness Enumeration: [CWE-73](https://cwe.mitre.org/data/definitions/73.html).

**Comment by henrybear327** [comment]
Will look into the logic [here](https://cs.opensource.google/go/go/+/refs/tags/go1.21.4:src/path/path.go;l=70) and try to port the path sanitizing logic over.
