### ISSUE TITLE
Introduce sound related system calls

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#152]
For the purpose of engaging in video game emulation, sound is of utmost importance. Unfortunately, there is a deficiency in the emulator's support for sound-related system calls, which could be effectively addressed through the integration of SDL2.

Reference:
* [FPGRARS](https://github.com/LeoRiether/FPGRARS): Fast Pretty Good RISC-V Assembly Rendering System

**Comment by ChinYikMing** [comment]
I am interested on solving this issue. May I be the assignee?

**Comment by jserv** [comment]
> I am interested on solving this issue. May I be the assignee?

Welcome. Please proceed. Keep in mind that the target verification scenarios might involve games like Doom and Quake, where we can make minimal changes to enable audio for these classic video games. Consequently, we could introduce high-level system calls based on SDL to meet the aforementioned expectations.

**Comment by ChinYikMing** [comment]
> You prosed 6 system calls for audio/sound. i.e.,
> 
> * play_sfx
> * play_music
> * stop_music
> * set_music_volume
> * setup_sound
> * shutdown_sound
> 
> Can you use fewer ones? 

Sure, we can use fewer system call via checking the type of request using register value. 
I think `setup_sound` and `shutdown_sound`  can be a pair, `play_music` and `play_sfx` can be a pair. 
Is it necessary to combine them?

**Comment by jserv** [comment]
> we can use fewer system call via checking the type of request using register value. I think `setup_sound` and `shutdown_sound` can be a pair, `play_music` and `play_sfx` can be a pair. Is it necessary to combine them?

Please take a moment to review the principles outlined in [Basics of the Unix Philosophy](http://www.catb.org/~esr/writings/taoup/html/ch01s06.html), particularly the concept of designing for simplicity and introducing complexity only when necessary.

In the context of our system, there are a single system call related to display management, along with an additional two system calls associated with event handling. Furthermore, I anticipate approximately 2 system calls for audio/sound manipulation. This means that we should aim to consolidate the existing APIs into a minimalist-style list of available system calls, rather than providing ruch-featured function prototypes. Your attention to maintaining simplicity while ensuring functionality is appreciated.

**Comment by jserv** [comment]
> In the context of our system, there are a single system call related to display management, along with an additional two system calls associated with event handling. Furthermore, I anticipate approximately 2 system calls for audio/sound manipulation.

Inspired by [Simple-SDL2-Audio](https://github.com/jakebesworth/Simple-SDL2-Audio), my preliminary concept for enhancing the sound/music system calls is to maintain two distinct system calls: `audio_setup` and `audio_control`.
* The `audio_setup` call would define the audio type, whether it's for sound or music. Only one music track can play concurrently, and it would loop. Multiple sound effects can be played concurrently, though an excessive number might lead to distortion.
* The `audio_control` call would then manage operations like play, pause, stop, and end.

**Comment by ChinYikMing** [comment]
> > In the context of our system, there are a single system call related to display management, along with an additional two system calls associated with event handling. Furthermore, I anticipate approximately 2 system calls for audio/sound manipulation.
> 
> Inspired by [Simple-SDL2-Audio](https://github.com/jakebesworth/Simple-SDL2-Audio), my preliminary concept for enhancing the sound/music system calls is to maintain two distinct system calls: `audio_setup` and `audio_control`.
> 
> * The `audio_setup` call would define the audio type, whether it's for sound or music. Only one music track can play concurrently, and it would loop. Multiple sound effects can be played concurrently, though an excessive number might lead to distortion.
> * The `audio_control` call would then manage operations like play, pause, stop, and end.

I already named them as `sound_manage` and `sound_control`. Is it OK?

**Comment by jserv** [comment]
> I already named them as sound_manage and sound_control. Is it OK?

I suggest adhering to the terminologies employed in SDL and its related libraries. It is important to provide clear explanations of the terms you intend to modify.
