### ISSUE TITLE
Cache tests fail after the enforcement of newline at the end of files

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#155]
Issue #154 enforces [a newline at the end of files](https://medium.com/@alexey.inkin/how-to-force-newline-at-end-of-files-and-why-you-should-do-it-fdf76d1d090e), with the exception of cache tests, which are excluded due to failures.

The way to reproduce:
```shell
$ git ls-files -z |  while IFS= read -rd '' f; do if file --mime-encoding "$f" | grep -qv binary; then tail -c1 < "$f" | read -r _ || echo >> "$f"; fi; done
$ make tests
```

Then, the error would be caught.
```
Running lfu/cache-new ... cmp: EOF on build/cache/lfu/cache-new.out after byte 10, line 1
Failed.
make: *** [run-test-cache] Error 1
```

**Comment by visitorckw** [comment]
I have discovered that this issue is due to the addition of newline characters at the end of input files used for testing. The existing test code fails to correctly match the "FREE" instruction on the last line of each input file. Therefore, simply changing the matching code from ```strcmp(arr[0], "FREE")``` to ```strcmp(arr[0], "FREE\n")``` can resolve this issue.

**Comment by visitorckw** [comment]
I noticed that this issue was assigned to @qwe661234 three months ago, but I haven't observed any recent activity on it. If assistance is still needed, would it be possible for me to take over and address this? I believe I can resolve this issue quickly.

**Comment by jserv** [comment]
> I noticed that this issue was assigned to @qwe661234 three months ago, but I haven't observed any recent activity on it. If assistance is still needed, would it be possible for me to take over and address this? I believe I can resolve this issue quickly.

Yes, please go ahead.
