### ISSUE TITLE
rv_histogram static analysis tool behaves weired on build/hello.elf

### ISSUE THREAD

**Issue by ChinYikMing** [sysprog21/rv32emu#190]
The sample output of `unknown`  is weird

sample output:
`+---------------------------------------------+
| RV32 Target Instruction Frequency Histogram |
+---------------------------------------------+
  1. addi       0.50% [9         ] ***************************************************************************************************************************
  2. unknown    0.28% [5         ] ********************************************************************
  3. jal        0.17% [3         ] *****************************************
  4. ecall      0.11% [2         ] ***************************
  5. nop        0.06% [1         ] *************
  6. auipc      0.06% [1         ] *************
  7. beq        0.06% [1         ] *************
  8. cnop       0.06% [1         ] *************
  9. lui        0.00% [0         ] 
 10. jalr       0.00% [0         ] `

**Comment by jserv** [comment]
Close in favor of #191
