### ISSUE TITLE
Study "A tale of binary translation"

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#219]
[A tale of binary translation](https://github.com/Amanieu/a-tale-of-binary-translation) is an informative talk on RISC-V emulator development. In particular, the [block linking](https://github.com/Amanieu/a-tale-of-binary-translation/blob/master/slides.pdf) part section outlines some effective enhancements, including:
* Finding the next function to execute.
* Constant propagation.
* Jump caches and resolvers.

These improvements resulted in a 2.2x speedup. The "Looking Forward" section is also worth studying.

Expected actions:
* Summarize the talk ([video](https://youtu.be/Avp55U2JFcQ))
* Create the issues associated with potential enhancements

**Comment by qwe661234** [comment]
# A tale of binary translation
The talk introduces the basic concept of the RISC-V emulator and discusses how to improve its performance. It applies various techniques, including:
## 1. Finding the next function to execute && Jump caches and resolvers
The compilation unit of the emulator is a basic block, so it need to link the next translation block. As shown in the [slides](https://github.com/Amanieu/a-tale-of-binary-translation/blob/master/slides.pdf), the cost of compilation is heavy. On the contrary, the compilation unit in `rv32emu` is all basic blocks within hotspot path. The primary focus of this implementation is to reduce the compiler invocation time. 
## 2. Custom calling convention
1. jump to the next function directly using a `tail call` which doesn’t increase stack usage on each call. In the `rv32emu`, we have imported this techniques.
2. For compilers that do not support `tail call`, we can pass the EmulatorState directly as arguments to the next function. This approach avoids the need to load/store EmulatorState in memory.
## 3. low-level code generator 
As shown in the [slides](https://github.com/Amanieu/a-tale-of-binary-translation/blob/master/slides.pdf), the cost of compilation is heavy. Actually, we don’t need the full power of compiler, most of the work in parsing and type-checking our generated code is wasted. Maybe we can use some low-level code generators like `Cranelift` and translate RISC-V instruction into code generators' IR by using API calls.

## 4. Multiple threads
Supporting multiple thread in the emulated system makes everything more complicated :(
## 5. Tiered compilation
* Multiple back-ends can be used simultaneously:
    * The interpreter works for cold path
    * The JIT works for hot path

As shown in the [slides](https://github.com/Amanieu/a-tale-of-binary-translation/blob/master/slides.pdf), the interpreter tracks how often a basic block is executing, and trigger JIT compilation upon reaching a threshold. The implementation is the same as `rv32emu`. 

Another point is this implementation allows JIT compilation to happen in a background thread, while the interpreter continues until compilation has finished. `rv32emu` unsupport this now, we need to wait until JIT compilation finish. 
## 6. Persistent code caching
We can avoid the cost of translation entirely by loading pre-translated code. 
There are two methods in the talk to generate code
1. Translated code can be saved to disk after it has been JIT-compiled. This is simpler, but the  first run of an applications still suffers from the cost of translation.
2. An application can be translated ahead of time by analyzing the compiled binary and locating all of the code blocks within it. This is often done when an application is installed, but this is difficult and it need a static analyzer.

## Reference
* [slides](https://github.com/Amanieu/a-tale-of-binary-translation/blob/master/slides.pdf)
* [videos](https://www.youtube.com/watch?v=Avp55U2JFcQ&ab_channel=RustNationUK)

**Comment by jserv** [comment]
Considered as DONE.
