### ISSUE TITLE
Incorrect timestamp rendered on benchmark page

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#225]
The recent commit ab3e58a20db5bfad2adb9bb90838a4ae5b7b649a, initiated benchmarking through the CI pipeline. However, there was an issue with the timestamp displayed on the [benchmark page](https://sysprog21.github.io/rv32emu-bench/). To illustrate this, consider the Dhrystone benchmark: the start date is listed as 2023-09-11, while the end date is 2022-12-07, which must be logically later than the start date.

**Comment by ChinYikMing** [comment]
The fact that the timestamp of the commit from the GitHub API is not the actual local time is really strange, therefore I update it to the Unix time, which logically makes the date of the most recent commit to be later than the previous commit.

Closed by rv32emu-bench's commit: b4211b7

**Comment by jserv** [comment]
Confirmed. Thank @ChinYikMing for fixing.
