### ISSUE TITLE
Interpreter should manipulate pc in registers when possible

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#241]
The current interpreter is empowered by tail-call optimization (TCO), which keeps most operations in registers. Slow paths are implemented as simple jumps and do not impact register allocation. Each opcode handler, defined using `RVOP` macro, includes the statement `rv->PC += ir->insn_len`. The program counter (`pc`) can be manipulated using [continuation-passing style](https://en.wikipedia.org/wiki/Continuation-passing_style), taking advantage of TCO, instead of frequent memory access.

Check [hawk/src/vm.c](https://github.com/djwatson/hawk/blob/main/src/vm.c) for reference.

**Comment by jserv** [comment]
Let's analyze `NOP` which is defined as following:
```c
/* RVOP(nop, { rv->X[rv_reg_zero] = 0; }) */
static bool do_nop(riscv_t *rv, const rv_insn_t *ir)
{
    rv->csr_cycle++;
    rv->X[rv_reg_zero] = 0;
nextop:
    rv->PC += ir->insn_len;
    if (unlikely(RVOP_NO_NEXT(ir)))
        return true;
    const rv_insn_t *next = ir->next;
    MUST_TAIL return next->impl(rv, next);
}
```

It is translated into the x86-64 assembly below:
```
000000000000b1f0 <do_nop>:
    b1f0:       48 83 87 a8 01 00 00    addq   $0x1,0x1a8(%rdi)
    b1f7:       01 
    b1f8:       c7 47 58 00 00 00 00    movl   $0x0,0x58(%rdi)
    b1ff:       0f b6 46 1c             movzbl 0x1c(%rsi),%eax
    b203:       01 87 d8 00 00 00       add    %eax,0xd8(%rdi)
    b209:       0f b6 46 1d             movzbl 0x1d(%rsi),%eax
    b20d:       0a 87 10 01 00 00       or     0x110(%rdi),%al
    b213:       75 0b                   jne    b220 <do_nop+0x30>
    b215:       48 8b 76 38             mov    0x38(%rsi),%rsi
    b219:       ff 66 20                jmpq   *0x20(%rsi)
    b21c:       0f 1f 40 00             nopl   0x0(%rax)
    b220:       c3                      retq   
    b221:       66 66 2e 0f 1f 84 00    data16 nopw %cs:0x0(%rax,%rax,1)
    b228:       00 00 00 00 
    b22c:       0f 1f 40 00             nopl   0x0(%rax)
```

Two add instructions correspond to variable increments: `rv->csr_cycle++` and `rv->PC += ir->insn_len`. Avoiding memory operations with registers is expected to reduce instruction latency.

**Comment by qwe661234** [comment]
Because the parameter we pass is the pointer points to the memory address of `rv`, any operation on `rv` member needs memory operations. If we want to avoid this, we should find out two host register that does not used by host program (or use prologue and epilogue to maintain them) and store `rv->csr_cycle` and `rv->PC` into these two register. However, to achieve this, handwriting assembly code is needed.

**Comment by qwe661234** [comment]
> Because the parameter we pass is the pointer points to the memory address of `rv`, any operation on `rv` member needs memory operations. If we want to avoid this, we should find out two host register that does not used by host program (or use prologue and epilogue to maintain them) and store rv->csr_cycle and rv->PC into these two register. However, to achieve this, handwriting assembly code is needed.

**Comment by jserv** [comment]
> Because the parameter we pass is the pointer points to the memory address of `rv`, any operation on `rv` member needs memory operations. If we want to avoid this, we should find out two host register that does not used by host program (or use prologue and epilogue to maintain them) and store `rv->csr_cycle` and `rv->PC` into these two register. However, to achieve this, handwriting assembly code is needed.

It is possible to specify the registers we want without having to write the entire implementation in assembly. See [ocaml-multicore/ocaml-multicore/runtime/interp.c](https://github.com/ocaml-multicore/ocaml-multicore/blob/5.00/runtime/interp.c#L204-L207):
```c
#ifdef __x86_64__
#define PC_REG asm("%r15")
#define SP_REG asm("%r14")
#define ACCU_REG asm("%r13")
#endif
...
/* The interpreter itself */

value caml_interprete(code_t prog, asize_t prog_size)
{
#ifdef PC_REG
  register code_t pc PC_REG;
  register value * sp SP_REG;
  register value accu ACCU_REG;
#else
  register code_t pc;
  register value * sp;
  register value accu;
#endif
  ..
```

**Comment by jserv** [comment]
[Pyston](https://github.com/pyston/pyston) is a performance-optimizing JIT for Python, defining its custom calling convention. See [pyston/Python/aot_ceval_jit_helper.c](https://github.com/pyston/pyston/blob/pyston_main/Python/aot_ceval_jit_helper.c):
```c
// this defines our custom calling convention
// we only define the ones the helpers are currently using because else gcc will completely
// avoid using this registers even though it could safely use them
#if __aarch64__
register PyObject** stack_pointer asm("x23");
register PyFrameObject* f asm("x19");
register PyThreadState* tstate asm("x22");
#if PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION >= 10
register PyTraceInfo* trace_info asm("x24");
#endif
#else
register PyObject** stack_pointer asm("r12");
register PyFrameObject* f asm("r13");
register PyThreadState* tstate asm("r15");
#if PY_MAJOR_VERSION == 3 && PY_MINOR_VERSION >= 10
register PyTraceInfo* trace_info asm("rbx");
#endif
#endif
```

**Comment by qwe661234** [comment]
Because `register` keyword can only use in local variable, we can pass the frequently used `rv` fields as parameter alternatively. We can check the assembly code of this [branch](https://github.com/qwe661234/rv32emu/tree/manipulate_register).
```
000000000000a6a0 <do_nop>:
    a6a0:	c7 47 58 00 00 00 00 	movl   $0x0,0x58(%rdi)
    a6a7:	48 83 c2 01          	add    $0x1,%rdx
    a6ab:	0f b6 46 1c          	movzbl 0x1c(%rsi),%eax
    a6af:	01 87 d8 00 00 00    	add    %eax,0xd8(%rdi)
    a6b5:	0f b6 46 1d          	movzbl 0x1d(%rsi),%eax
    a6b9:	0a 87 10 01 00 00    	or     0x110(%rdi),%al
    a6bf:	75 0f                	jne    a6d0 <do_nop+0x30>
    a6c1:	48 8b 76 38          	mov    0x38(%rsi),%rsi
    a6c5:	ff 66 20             	jmp    *0x20(%rsi)
    a6c8:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
    a6cf:	00 
    a6d0:	c3                   	ret    
    a6d1:	66 66 2e 0f 1f 84 00 	data16 cs nopw 0x0(%rax,%rax,1)
    a6d8:	00 00 00 00 
    a6dc:	0f 1f 40 00          	nopl   0x0(%rax)
```
In this branch, I pass `csr_cycle` as parameter and the instruction become `add    $0x1,%rdx` instead of memory operation.

**Comment by qwe661234** [comment]
we can pass the frequently used rv fields `csr_cycle` and `PC` as parameter and check the assembly code of this [branch](https://github.com/qwe661234/rv32emu/tree/manipulate_register).
```
000000000000a9b0 <do_nop>:
    a9b0:	41 89 c8             	mov    %ecx,%r8d
    a9b3:	c7 47 58 00 00 00 00 	movl   $0x0,0x58(%rdi)
    a9ba:	0f b6 4e 1c          	movzbl 0x1c(%rsi),%ecx
    a9be:	48 83 c2 01          	add    $0x1,%rdx
    a9c2:	0f b6 46 1d          	movzbl 0x1d(%rsi),%eax
    a9c6:	44 01 c1             	add    %r8d,%ecx
    a9c9:	0a 87 10 01 00 00    	or     0x110(%rdi),%al
    a9cf:	75 0f                	jne    a9e0 <do_nop+0x30>
    a9d1:	48 8b 76 38          	mov    0x38(%rsi),%rsi
    a9d5:	ff 66 20             	jmp    *0x20(%rsi)
    a9d8:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
    a9df:	00 
    a9e0:	48 89 97 a8 01 00 00 	mov    %rdx,0x1a8(%rdi)
    a9e7:	89 8f d8 00 00 00    	mov    %ecx,0xd8(%rdi)
    a9ed:	c3                   	ret    
    a9ee:	66 90                	xchg   %ax,%ax
```

The operands of two x86 `add` instructions for `csr_cycle` and `PC` is all registers, instead of memory location. Moreover, we observe that we need a memory operation to get `ir->insn_len` by `a9c2:	movzbl 0x1d(%rsi),%eax`, maybe we can assign insn_len `4` or `2` directly.

```
000000000000b520 <do_nop>:
    b520:	39407424 	ldrb	w4, [x1, #29]
    b524:	aa0003e5 	mov	x5, x0
    b528:	b900581f 	str	wzr, [x0, #88]
    b52c:	91000442 	add	x2, x2, #0x1
    b530:	39444007 	ldrb	w7, [x0, #272]
    b534:	39407026 	ldrb	w6, [x1, #28]
    b538:	2a070084 	orr	w4, w4, w7
    b53c:	72001c84 	ands	w4, w4, #0xff
    b540:	0b0300c3 	add	w3, w6, w3
    b544:	540000a1 	b.ne	b558 <do_nop+0x38>  // b.any
    b548:	f9401c21 	ldr	x1, [x1, #56]
    b54c:	f9401024 	ldr	x4, [x1, #32]
    b550:	aa0403f0 	mov	x16, x4
    b554:	d61f0200 	br	x16
    b558:	2a0403e0 	mov	w0, w4
    b55c:	b900d8a3 	str	w3, [x5, #216]
    b560:	f900d4a2 	str	x2, [x5, #424]
    b564:	d65f03c0 	ret
```
For architecture aarch64, we also discover that the operands of two arm `add` instructions for `csr_cycle` and `PC` is all registers, instead of memory location and it needs a memory operation to get `ir->insn_len` by `b534: ldrb	w6, [x1, #28]`.

**Comment by jserv** [comment]
> maybe we can assign insn_len `4` or `2` directly.

In commit 80cac224e5df86fbe3c24af6c5a16b5bf06f21cf, `C.NOP` is mapped to `NOP`. Do you think the `rv_insn_nop` handler might encounter issues with the proposed changes? Should we consider duplicating `rv_insn_cnop`?

**Comment by qwe661234** [comment]
> > maybe we can assign insn_len `4` or `2` directly.
> 
> In commit [80cac22](https://github.com/sysprog21/rv32emu/commit/80cac224e5df86fbe3c24af6c5a16b5bf06f21cf), `C.NOP` is mapped to `NOP`. Do you think the `rv_insn_nop` handler might encounter issues with the proposed changes? Should we consider duplicating `rv_insn_cnop`?

Actually, we have encountered the issues about incorrect insn_len in arch_test, we need to unmap C.NOP

**Comment by jserv** [comment]
> For architecture aarch64, we also discover that the operands of two arm add instructions for `csr_cycle` and `PC` is all registers, instead of memory location and it needs a memory operation to get `ir->insn_len` by `b534: ldrb w6, [x1, #28]`.

It sounds great. The proposed changes have the potential to align the behavior closely with that of a hand-coded assembly version, all while offering enhanced portability and flexibility for future modifications. We can incorporate this strategy into our upcoming reports.

**Comment by jserv** [comment]
If remote GDB support is turned off (i.e., `ENABLE_GDBSTUB=0`), along with the proposed changes, performance can be generally improved due to better code generation. I observed a 5% improvement in Dhrystone benchmarks in this scenario.

**Comment by jserv** [comment]
> If remote GDB support is turned off (i.e., `ENABLE_GDBSTUB=0`), along with the proposed changes, performance can be generally improved due to better code generation. I observed a 5% improvement in Dhrystone benchmarks in this scenario.

Remote GDB support is disabled by default. See commit ce27e8020e129cdc5f7fec8bb90fff52d9bafde7
