### ISSUE TITLE
Build with Profile-Guided Optimization

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#242]
[Profile-Guided Optimization](https://en.wikipedia.org/wiki/Profile-guided_optimization) (PGO) involves adding probes to a compiled binary, running the binary, and then using the runtime information to recompile it, with the aim of improving its performance.

Apply the following changes:
```diff
--- a/Makefile
+++ b/Makefile
@@ -4,10 +4,14 @@ include mk/toolchain.mk
 OUT ?= build
 BIN := $(OUT)/rv32emu
 
-CFLAGS = -std=gnu99 -O2 -Wall -Wextra
+CFLAGS = -std=gnu99 -O2 -DNDEBUG -Wall -Wextra
 CFLAGS += -Wno-unused-label
 CFLAGS += -include src/common.h
 
+# Profile-Guided Optimization]
+CFLAGS += -flto $(PGO_CFLAGS)
+LDFLAGS += $(PGO_LDFLAGS)
+
 # Set the default stack pointer
 CFLAGS += -D DEFAULT_STACK_ADDR=0xFFFFE000
 # Set the default args starting address
```

Do profiling:
```shell
$ PGO_CFLAGS="-fprofile-generate -fprofile-update=prefer-atomic" \
   PGO_LDFLAGS="-lgcov --coverage" make clean all
$ rm build/*.gcda
$ build/rv32emu build/coremark.elf
```

Rebuild using the profiling data:
```shell
$ PGO_CFLAGS="-fprofile-use -fprofile-correction -fprofile-partial-training" make clean all
```

And then `build/rv32emu` is the final executable with PGO.

Experiment results on AMD Ryzen Threadripper 2990WX 32-Core Processor with GCC-10.

| Metrics | original | PGO |
|-------:|--------:|------:|
| Dhrystone | 901 DMIPS |  1569 DMIPS |
| CoreMark | 993 iter/s | 1048.4 iter/s |

Reference:
* [Optimizing Interpreters by Tuning Opcode Orderings on Virtual Machines for Modern Architectures](https://dl.acm.org/doi/10.1145/2093157.2093183)
* [awesome-pgo](https://github.com/zamazan4ik/awesome-pgo/)

**Comment by qwe661234** [comment]
Here is experiment results on Intel Core i7-11700 @ 2.50GHz with GCC-11

|Metrics	|original	|PGO|
|--------|--------|--------|
|Dhrystone	|2146.5 DMIPS	|2385 DMIPS|
|CoreMark	|1717.9 iter/s	|1741.9 iter/s|

**Comment by jserv** [comment]
Given that the effectiveness of Profile-Guided Optimization (PGO) varies significantly based on both the hardware's microarchitecture and the optimization capabilities of compilers, it becomes challenging to precisely quantify its performance benefits. Therefore, considering these variables and the difficulty in establishing consistent measures, I am inclined to close this issue.
