### ISSUE TITLE
Implement input event specific system calls for SDL support

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#27]
`rv32emu` comes with experimental SDL support, which can render the frame via SDL2. However, it is unlikely useful to most visual applications, and there should be some relevant system calls associated with input events.

Expected output:
1. Add `syscall_poll_event` amd `syscall_get_input` which listen to keyboard/mouse events abstracted by SDL2.
2. Provide a neat and minimal test suite (RV32 ELF executables) for SDL support.

**Comment by alanjian85** [comment]
I guess we could create a fork of `quakembd` in the `sysprog21` organization, and use mechanisms like CMake's subdirectory or Makefile directly to automate the build process of the RV32 elf. even though it may add an external submodule dependency, it would be more convenient to review the source, instead of checking the git log and find the source repo's link.

**Comment by jserv** [comment]
[sysprog21/quake-embedded](https://github.com/sysprog21/quake-embedded) is now ready for testing. Please check `git log` for build instructions. It can be regarded the testbed for new SDL oriented system calls.

**Comment by jserv** [comment]
[smunaut/doom_riscv](https://github.com/smunaut/doom_riscv) would be the next target to facilitate SDL oriented system call. Check [its forks](https://github.com/smunaut/doom_riscv/network) as well.

**Comment by jserv** [comment]
commit [5d782b8](https://github.com/sysprog21/rv32emu/commit/5d782b841000d7c1a12eed6f44ea0d8c8f3f8125) introduces a new system call, `poll_event`, which attempts to pop events from the internal event queue and returns input specific event information to the user code. The next step is to ensure both Quake and Doom can facilitate the new system call.

**Comment by alanjian85** [comment]
I opened a pull request https://github.com/sysprog21/quake-embedded/pull/1.

**Comment by alanjian85** [comment]
We should have another system call to enable and disable the relative mouse mode. This system call should be used to sync with Quake, enable relative mode when the user is playing and disable it when the user opens the menu.

**Comment by jserv** [comment]
> I opened a pull request [sysprog21/quake-embedded#1](https://github.com/sysprog21/quake-embedded/pull/1).

Great. Please send a pull request which updates Quake ELF executable file along with basic operation manual.
