### ISSUE TITLE
CI: Generate Docker image with Alpine Linux

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#286]
Currently, the CI pipeline can generate Docker images, but the size of these images is quite large, which is not ideal for showcasing a small yet powerful RISC-V instruction set simulator. To address this, we can consider rebuilding the Docker image using [Alpine Linux](https://www.alpinelinux.org/), a security-focused, lightweight Linux distribution that uses musl libc and busybox. This would not only reduce the image size but also provide a minimal runtime environment.

**Comment by henrybear327** [comment]
This will take a while, as the package management system is `apk` and the package names are usually different from `apt`. 

I will adapt accordingly.

**Comment by visitorckw** [comment]
The substantial size of the current Docker image is primarily attributed to the riscv-gnu-toolchain, surpassing 1GB. While transitioning to Alpine as the base image can reduce the size (from around 100 MB to approximately 5 MB), it's still likely that the overall image size may well exceed 1GB.

**Comment by henrybear327** [comment]
Maybe we don't need to keep around all the binaries compiled from the toolchain. I will take a look over there! Thanks for the pointers.

**Comment by henrybear327** [comment]
Image size evolution (the total size shown is accumulative, with respect to the previously listed items) 

- `Ubuntu:22:04` -> 69.4 MB
- Copying the source code (`tests` folder itself is about 500 MB) ->  831 MB
- Install extra packages (e.g. `libsdl2-dev`) -> 1.49GB

For the GCC toolchain
- Using xpack toolchain -> 3.56GB
- Copying from the self-built GCC image -> 2.12GB

**Comment by jserv** [comment]
> Maybe we don't need to keep around all the binaries compiled from the toolchain. I will take a look over there! Thanks for the pointers.

I don't believe it is necessary to include the prebuilt GNU Toolchain for RISC-V in the Docker image. Users interested in running RISC-V Architecture Tests can manually download the prebuilt toolchain via package managers like [xpack](https://xpack.github.io/). The Docker image should provide the `rv32emu `executable, sample RISC-V ELF files, and auxiliary scripts for downloading the GNU Toolchain and sail as needed.

**Comment by henrybear327** [comment]
> sample RISC-V ELF files

A subset of the elf files from the build directory will be kept

> auxiliary scripts for downloading the GNU Toolchain and sail as needed

Will add this in the PR #290

**Comment by henrybear327** [comment]
I believe the current image size and build time are acceptable after merging https://github.com/sysprog21/rv32emu/pull/290.

**Comment by jserv** [comment]
> I believe the current image size and build time are acceptable after merging #290.

Actually, the image size remains larger than expected. We do need an effective way to generate smaller Docker images.
