### ISSUE TITLE
Consolidate public header by integrating src/state.h

### ISSUE THREAD

**Issue by ChinYikMing** [sysprog21/rv32emu#301]
To fully(as much as possible) leverage rv32emu's core, I've attempted to export the `state_new` function from "state.h" for usage in WebAssembly, but it doesn't appear to be functioning. It works after splitting to "state.[ch]". I think the reason is that `state_new` is not found in any translation units since they have been inlined by the compiler.

May I know any concerns with this change? I might send a PR for this modification if it doesn't. 

Refer to #75

**Comment by jserv** [comment]
The `src/state.h` header originally served as a testament to my efforts in refining the APIs for the RISC-V instruction set simulator in the `src/riscv.h` header. It would be more efficient to merge `src/state.h` into `src/riscv.[ch]`, aligning it with the improved and consistent public functions. For reference, you can review the [riscv.h](https://github.com/sysprog21/semu/blob/master/riscv.h) file in SEMU.
