### ISSUE TITLE
Failed to build using emcc when ENABLE_SDL=1 is set outside macOS

### ISSUE THREAD

**Issue by ChinYikMing** [sysprog21/rv32emu#381]
Error:
```
In file included from src/syscall_sdl.c:16:
In file included from /usr/include/SDL2/SDL.h:32:
In file included from /usr/include/SDL2/SDL_main.h:25:
In file included from /usr/include/SDL2/SDL_stdinc.h:31:
/usr/include/SDL2/SDL_config.h:4:10: fatal error: 'SDL2/_real_SDL_config.h' file not found
    4 | #include <SDL2/_real_SDL_config.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

The linker links system SDL library instead of Emscripten-port SDL library in commit 446b95b without properly checking which compiler is used.

**Comment by jserv** [comment]
How can we validate the availability of SDL package shipped with Emscripten? Is it possible that emcc exists without the corresponding SDL headers?

**Comment by ChinYikMing** [comment]
> How can we validate the availability of SDL package shipped with Emscripten? Is it possible that emcc exists without the corresponding SDL headers?

`emcc` will fetch and build Emscripten-port SDL library so it is buildable even no SDL library are installed in system.
