### ISSUE TITLE
Help with the Emulator

### ISSUE THREAD

**Issue by PedroLSF** [sysprog21/rv32emu#386]
I'm trying to emulate my binary from a hello.s, but I'm taking this whether it's .elf or binary.
Can anyone help me?
![image](https://github.com/sysprog21/rv32emu/assets/85000470/d6b357d1-7f15-41bc-a1c2-4d8f671c5314)

**Comment by ChinYikMing** [comment]
Could you determine the toolchains you used and what is the format type of your ELF (you can use `file` command to verify this)?

**Comment by jserv** [comment]
> I'm trying to emulate my binary from a hello.s, but I'm taking this whether it's .elf or binary. Can anyone help me? 

Sure! Please try this: https://github.com/sysprog21/rv32emu/tree/master/tests/asm-hello

After the GNU toolchain for RISC-V is correctly set up, you can compile the 'hello' program using 'make', which results in the creation of an RV32I bare-metal ELF file.

By the way, don't paste the screenshot which contains plaintext messages.

**Comment by PedroLSF** [comment]
Okay, I managed to complete the steps.
Firstly, sorry for the screenshot @jserv and @ChinYikMing 

I am looking for a simulator that can be used as an Online Judge system within the college, where it will receive a Risc-V code and will inject an input.txt with a set of inputs and generate an output.txt with a set about to leave.

Can you tell me if it would be possible with the rv32emu?

So I'm trying to make a code that reads and prints an integer to the console, but from what I saw, it can't read integers and only prints as a string, I made this code based on hello.S:

```
.org 0
.global _start

/* newlib system calls */
.set SYSEXIT,  93
.set SYSWRITE, 64
.set SYSREAD, 63

.section .rodata
str: .ascii "Type something: "
     .set str_size, .-str
buffer: .space 256

.text
_start:
    # Print "Type something: "
    li a7, SYSWRITE     # "write" syscall
    li a0, 1            # 1 = standard output (stdout)
    la a1, str          # load address of prompt string
    li a2, str_size     # length of prompt string
    ecall               # invoke syscall to print the prompt

    # Read input from console
    li a7, SYSREAD      # "read" syscall
    li a0, 0            # 0 = standard input (stdin)
    la a1, buffer       # Address of buffer to store input
    li a2, 256          # Maximum number of characters to read
    ecall               # invoke syscall to read input

    # Print the input back to console
    li a7, SYSWRITE     # "write" syscall
    li a0, 1            # 1 = standard output (stdout)
    la a1, buffer       # Address of input buffer
    li a2, 256          # Length of input string (same as buffer)
    ecall               # invoke syscall to print the input

    # Exit the program
    li a7, SYSEXIT      # "exit" syscall
    add a0, x0, 0       # Use 0 return code
    ecall               # invoke syscall to terminate the program

```

Can you tell me if there is a syscall or any way to read and write other types of data?

**Comment by jserv** [comment]
> I am looking for a simulator that can be used as an Online Judge system within the college, where it will receive a Risc-V code and will inject an input.txt with a set of inputs and generate an output.txt with a set about to leave.
> Can you tell me if it would be possible with the rv32emu?

I think it is feasible to integrate rv32emu into online judge system.
Can you show the detailed command sequence you managed to assemble and link? You should indicate the information about the GNU Toolchain you are using.

**Comment by PedroLSF** [comment]
Sure!
For the above code, I used this command sequence:
```
riscv64-unknown-elf-as -R -march=rv32i -mabi=ilp32 -o read.o read.S
riscv64-unknown-elf-ld -o read.elf --oformat=elf32-littleriscv read.o
```

In this case, I didn't use a loader.
In the code, I read and printed a data, and from what I saw, the print syscall prints it as a string.

So, what I want to check is if, for example, let's assume that it will evaluate a Risc-v code that reads 2 integer values and does the sum (add) or multiplication (mul) and prints the value of that sum/multiplication. Is this already possible or does it need to be developed?

Thank you in advance.

**Comment by jserv** [comment]
You should specify the linker script. See [hello.ld](https://github.com/sysprog21/rv32emu/blob/master/tests/asm-hello/hello.ld) as an example. You have to pass the option `-T hello.ld` to linker. See the corresponding [Makefile](https://github.com/sysprog21/rv32emu/blob/master/tests/asm-hello/Makefile) as well.

**Comment by PedroLSF** [comment]
Right.
I had already taken a look.
Sorry, but I don't understand how the loader will help in reading the data type, for example, instead of reading a string, it will read an integer to perform the sum.
Can you give me an example?

**Comment by jserv** [comment]
> Sorry, but I don't understand how the loader will help in reading the data type, for example, instead of reading a string, it will read an integer to perform the sum.

From the perspective of RISC-V processors or CPU simulators like rv32emu, understanding data types is not required. Instead, the Instruction Set Architecture (ISA) focuses on offsets, which are determined by the assembler and compiler, in collaboration with the programmer's high-level programming concepts.

Check the [slides](https://selfie.cs.uni-salzburg.at/slides) that provide a comprehensive introduction to the RISC-V low-level programming.

By the way, rv32emu primarily functions as an ISA simulator rather than a loader. While it has the ability to load ELF files, this capability is limited.

**Comment by PedroLSF** [comment]
Dear @jserv ,

Thank you very much for the answer and the references, they enlighten me a lot.

But I was analyzing it and I believe I wrote an incomplete question or maybe I couldn't express myself correctly, I apologize for that and I would like to complement my question.

So I'll use this code snippet below as an example to explain what I'm looking for:

```
.text
_start:
     li a7, 5 # Read an Integer
     ecall
     mv t0, a0 # Read A

     li a7, 5 # Read an Integer
     ecall
     mv t1, a0 # Read B
 
     add s2, t0, t1 #s2 = a + b

     li a7, 1 #Print the entire in a7
     mv a0, s2 #Put the integer in a0
     ecall #Save
```
Previously I was using RARS to perform my experiments and I used the RISC-V standard specification to do this sum of 2 integers, where I use ecall 5 to read an integer and ecall 1 to print an integer.

Using ecall 5 to read an integer: 
```
 li a7, 5 # Read an Integer
 ecall
 mv t0, a0 # Read A
 ```  

Using ecall 1 to print an integer:
```
 li a7, 1 #Print the entire in a7
 mv a0, s2 #Put the integer in a0
 ecall #Save
 ```  
So, these are ecalls that are provided for in the standard that defines the ISA. However, I believe that this is not covered in the same way as RARS, as it is not listed in the supported syscalls and when using these syscalls, we end up getting an "unknown syscall" warning.

https://github.com/sysprog21/rv32emu/blob/44be737aeeb4f75cfb91b1ed7a9e4abc42b2e732/src/syscall.c#L26-L43

So, I wanted to know if anyone has already implemented this or if there has been interest or thought about implementing ecalls for reading and writing integers, floats and doubles?

Can rv32emu reproduce this RARS behavior?

**Comment by jserv** [comment]
> So, I wanted to know if anyone has already implemented this or if there has been interest or thought about implementing ecalls for reading and writing integers, floats and doubles?

I would stick to the syscalls defined in newlib. The original byte-oriented operation should make sense in most cases.

**Comment by PedroLSF** [comment]
Ok, but maybe at a teaching level it might be interesting to add these syscalls. Can you guide me on how to adapt/implement it?

Would I just have to add these syscalls and do the respective methods for each one?

**Comment by jserv** [comment]
> Ok, but maybe at a teaching level it might be interesting to add these syscalls. Can you guide me on how to adapt/implement it?

rv32emu was built [for education purpose](https://wiki.csie.ncku.edu.tw/arch/schedule). My adherence to the system calls defined in newlib aims to align with the de facto standards prevalent in embedded systems and system software programming. Please proceed to adjust the source code as necessary on your own.

**Comment by PedroLSF** [comment]
Understood.

I understand that the rv32emu was built for educational purposes, I am only searching in accordance with some requirements that were imposed/requested on me.

I apologize if I ended up inferring something that sounded wrong, and I am very grateful for the support and information provided here.

Thank you
