### ISSUE TITLE
Filter out message-less demo programs from WebAssembly demo page

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#390]
The [rv32emu-demo](https://sysprog21.github.io/rv32emu-demo/) currently includes a WebAssembly build of rv32emu, complete with assets and prebuilt RISC-V ELF files. However, some of these ELF files, intended for testing purposes, produce no output. To enhance the demonstration experience, we should remove any ELF files that do not display messages in the terminal.

**Comment by ChinYikMing** [comment]
> The [rv32emu-demo](https://sysprog21.github.io/rv32emu-demo/) currently includes a WebAssembly build of rv32emu, complete with assets and prebuilt RISC-V ELF files. However, some of these ELF files, intended for testing purposes, produce no output. To enhance the demonstration experience, we should remove any ELF files that do not display messages in the terminal.

I think the ELF files you are referring to are as follows:
- `lena.elf`
- `cc.elf`
- `chacha20.elf`
- `puzzle.elf`
- `line.elf`
- `captcha.elf`
