### ISSUE TITLE
Don't check out softfloat if no F extension is configured

### ISSUE THREAD

**Issue by kjhhgt76** [sysprog21/rv32emu#456]
Dear all,

I tried to disable floating point by modifying ENABLE_EXT_F ?= 1 to ENABLE_EXT_F ?= 0 inside Makefile.
But make still tries to get softfloat.
what is the problem?

Regards,

**Comment by visitorckw** [comment]
Hi @kjhhgt76 ,
I am unable to reproduce this issue.
I followed your instructions and changed ```ENABLE_EXT_F ?= 1``` to ```ENABLE_EXT_F ?= 0``` in the Makefile as shown below:
```diff
diff --git a/Makefile b/Makefile
index d835911..3ee6614 100644
--- a/Makefile
+++ b/Makefile
@@ -51,7 +51,7 @@ ENABLE_EXT_A ?= 1
 $(call set-feature, EXT_A)
 
 # Single-precision floating point instructions
-ENABLE_EXT_F ?= 1
+ENABLE_EXT_F ?= 0
 $(call set-feature, EXT_F)
 ifeq ($(call has, EXT_F), 1)
 AR := ar
```

After that, I ran ```make```, but I did not observe ```make``` attempting to compile or link ```softfloat```. Am I missing any necessary steps to reproduce this issue?

```
$ make
Check the file build/.config for configured items.
  CC    build/map.o
  CC    build/utils.o
  CC    build/decode.o
  CC    build/io.o
  CC    build/syscall.o
  CC    build/emulate.o
  CC    build/riscv.o
  CC    build/elf.o
  CC    build/cache.o
  CC    build/mpool.o
  CC    build/syscall_sdl.o
  CC    build/main.o
  LD    build/rv32emu
```

**Comment by kjhhgt76** [comment]
The problem is when I don't have src/softfloat/build/Linux-RISCV-GCC/Makefile
It will still try to do
git submodule update --init src/softfloat/ 
which I can't do in my system.

I am using Make 3.82
Not sure if the make version has problem.

Nonetheless, I can still disable floating point to Make by using command line argument.

**Comment by jserv** [comment]
> Nonetheless, I can still disable floating point to Make by using command line argument.

Can you run `make ENABLE_EXT_F=0 distclean all` and check again?

**Comment by kjhhgt76** [comment]
solved
