### ISSUE TITLE
Migrate to RISC-V Compatibility Framework (RISCOF)

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#49]
Recently, [RISC-V Architecture Test SIG](https://lists.riscv.org/g/sig-arch-test) refines the build system and introduces [RISC-V Compatibility Framework](https://riscof.readthedocs.io/en/latest/) (RISCOF) which enables testing of a RISC-V target (hard or soft implementations) against a standard RISC-V golden reference model using a suite of RISC-V architectural assembly tests. It implies dramatical incompatibility, and we would stick to the old framework based on GNU make at the moment. Quote from [riscv-arch-test](https://github.com/riscv-non-isa/riscv-arch-test/):
> The older 2.x version of the framework (based on Makefiles) can be found in a separate branch : [old-framework-2.x](https://github.com/riscv-non-isa/riscv-arch-test/tree/old-framework-2.x). This branch is officially no longer supported and all changes must occur on the main branch.

In order to synchronize with latest RISC-V Architecture Tests, we shall migrate.

**Comment by Risheng1128** [comment]
According to the commit [Riscof dev](https://github.com/riscv-non-isa/riscv-arch-test/pull/255), we can find out the change of riscv-arch-test about migrating to new RISCOF framework.

Major changes include:
- removal of Makefiles. The execution framework will now be controlled by the python based RISCOF tool.
- removal of referece signatures. The signatures will now be generated dynamically using a reference model via RISCOF.
- removal of obsolete test-environments.
- removal of targets compatible with old-framework-2.x
- removal of Migration doc

**Comment by jserv** [comment]
[neorv32-riscof](https://github.com/stnolting/neorv32-riscof) a port of the "RISCOF RISC-V Architectural Test Framework" to test the [NEORV32 RISC-V Processor](https://github.com/stnolting/neorv32) for compatibility to the RISC-V user and privileged ISA specifications.
