### ISSUE TITLE
Avoid repeated downloads for assets during test

### ISSUE THREAD

**Issue by jserv** [sysprog21/rv32emu#491]
After the successful integration of #474, our GitHub CI/CD pipeline now automatically publishes a tarball of the latest RISC-V executables, keeping the rv32emu source tree clean. However, we have noticed that the tarball is being downloaded multiple times during tests, leading to unnecessary delays. To improve this, we can cache the downloaded files beforehand and simply verify the extracted RISC-V executables during the testing phase.

**Comment by vacantron** [comment]
@ChinYikMing, can you remove [this line](https://github.com/sysprog21/rv32emu/blob/563af8b797a95ec219d9a9cf3817bf529b93f27f/mk/wasm.mk#L2) as the object file dependencies which added in #487? This will always trigger rebuilding `src/*` via executing `make all` at https://github.com/sysprog21/rv32emu/blob/563af8b797a95ec219d9a9cf3817bf529b93f27f/Makefile#L222

**Comment by ChinYikMing** [comment]
> @ChinYikMing, can you remove [this line](https://github.com/sysprog21/rv32emu/blob/563af8b797a95ec219d9a9cf3817bf529b93f27f/mk/wasm.mk#L2) as the object file dependencies which added in #487? This will always trigger rebuilding `src/*` via executing `make all` at
> 
> https://github.com/sysprog21/rv32emu/blob/563af8b797a95ec219d9a9cf3817bf529b93f27f/Makefile#L222

I would prefer to keep it and only add the `artifact` target to `deps_emcc` if `CC=emcc`, but not the way [it's](https://github.com/sysprog21/rv32emu/blob/563af8b797a95ec219d9a9cf3817bf529b93f27f/mk/wasm.mk#L2) currently written.

https://github.com/sysprog21/rv32emu/blob/563af8b797a95ec219d9a9cf3817bf529b93f27f/mk/wasm.mk#L2
