### ISSUE TITLE
Open quake and doom failed

### ISSUE THREAD

**Issue by Risheng1128** [sysprog21/rv32emu#64]
After merge the commit #62 , I find that the quake and doom can't be opened properly.
As long as I open quake or doom, both of them will crash immediately. Therefore, I 
think that there are some bugs in commit #62 .

**Comment by jserv** [comment]
Let's wait for the investigations from @alanjian85 .

**Comment by jserv** [comment]
WIP: https://github.com/sysprog21/quake-embedded/pull/7
