### ISSUE TITLE
Unexpected output when running rv32emu

### ISSUE THREAD

**Issue by maromaSamsa** [sysprog21/rv32emu#82]
I generate the ELF file from [this RISC-V source code](https://github.com/maromaSamsa/Computer_Arch2022/blob/50db073a5d356e61b21be4aca870a7400940416c/Lab2_RISC-V%20Toolchain/My%20asm%20code/my_asm.s), but I get a different output result when executing in [rv32emu](https://github.com/sysprog21/rv32emu/tree/336992f32ca9e3a497116ad872a93928eaf97ea8) and [Ripes](https://github.com/mortbopet/Ripes/tree/eb801efbb62c91b7acaaadfcfe303957b8436dc0)

How I generate it to ELF:
```shell = 
$ riscv-none-elf-gcc -march=rv32i -mabi=ilp32 -o my_asm.elf my_asm.s
```
The result I run in rv32emu:
```shell = 
$ build/rv32emu my_asm.elf
5
0
0
inferior exit code 0
```

The result I run in Ripes:
```
5
3
0
inferior exit code 0
```
which is also the result I expected.

--------------- edit ------------------
maybe there has some problem of `lw` instruction
these are my test data:
```
.data
arr1:    
        .byte 7, 1, 5, 3, 6, 4
arr2:    
        .byte 1, 1, 3, 5
arr3:    
        .byte 7, 5, 4, 3, 2
```

where `printArr` simply print each byte, with unrolling technique, I use load word instruction `lw` from address s1 to load 4 bytes in once. 
```
.text
main:  
        la     s1, arr1        # load arr1 address
        addi   s2, x0, 6       # lens of arr1
        jal    ra, printArr    # print each byte one by one 

        la     s1, arr2        # load arr2 address of prices in a1
        addi   s2, x0, 4       # store the size of prices in a2
        jal    ra, printArr    # next instruction store in rd register

        la     s1, arr3        # load arr3 address of prices in a1
        addi   s2, x0, 5       # store the size of prices in a2
        jal    ra, printArr    # next instruction store in rd register 
end:
        addi    a7, x0, 93	   # "exit" syscall is 93 in rv32emu
        addi	a0, x0, 0	   # set ret to 0
        ecall                  # program stop
```
Here was an output:
```
# arr 1
(load a word)
7
1
5
3
(load next word)
6
4
(end of arr 1)
# arr 2
(load a word)
1
1
0 (unexpected output occur starting from here)
0
(end of arr 2)
# arr3
(load a word)
0
0
0
0
(load next word)
0
(end of arr3)
```

**Comment by jserv** [comment]
@maromaSamsa, you shall provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (MRE) instead of hyperlinks. Edit the description of this issue to inline MRE.

**Comment by Risheng1128** [comment]
@maromaSamsa I want to check your problem. Does your problem is that the emulator executes wrong when instruction `la` is changed to instruction `lw` ?

Example:
```
la     s1, arr1    ->    lw    s1, arr1
```

**Comment by maromaSamsa** [comment]
> @maromaSamsa I want to check your problem. Does your problem is that the emulator executes wrong when instruction `la` is changed to instruction `lw` ?
> 
> Example:
> 
> ```
> la     s1, arr1    ->    lw    s1, arr1
> ```

Actually I am not sure, in [this RISC-V source code](https://github.com/maromaSamsa/Computer_Arch2022/blob/50db073a5d356e61b21be4aca870a7400940416c/Lab2_RISC-V%20Toolchain/My%20asm%20code/my_asm.s) I just use `la` to get address of the byte array, and use `lw` to load 4 byte value from the array.

Cause I had found that the unexpected output only occur when the size of the previous array is not equal to `multiples of four byte`, so I suspected that maybe their have some bug in `lw` or `la`.

**Comment by jserv** [comment]
> Cause I had found that the unexpected output only occur when the size of the previous array is not equal to `multiples of four byte`, so I suspected that maybe their have some bug in `lw` or `la`.

The concept of alignment is dependent upon the size of data. For word data the address is either multiple of 4 (aligned), or it is misaligned. @maromaSamsa, you can now prepare a revised MRE which reflects the above findings.

**Comment by maromaSamsa** [comment]
> > Cause I had found that the unexpected output only occur when the size of the previous array is not equal to `multiples of four byte`, so I suspected that maybe their have some bug in `lw` or `la`.
> 
> The concept of alignment is dependent upon the size of data. For word data the address is either multiple of 4 (aligned), or it is misaligned. @maromaSamsa, you can now prepare a revised MRE which reflects the above findings.

Please check this [commit](https://github.com/maromaSamsa/Computer_Arch2022/commit/7845c59dc6223735fdc50bb3e486f1d988c749fa)

the output is normal when you change the test case
```rust= 
.data
arr1:
	.byte 48, 49, 50 # this will cause unexpected output
	#.byte 48, 49, 50, 51 # check this
```

PS: sorry for the wrong term in this commit, is `MRE`([minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)) not `MSE`([Mean squared error](https://en.wikipedia.org/wiki/Mean_squared_error)).

**Comment by qwe661234** [comment]
@maromaSamsa, I already checked this [commit](https://github.com/maromaSamsa/Computer_Arch2022/commit/7845c59dc6223735fdc50bb3e486f1d988c749fa). The reason why test case  `.byte 48, 49, 50` cause unexpected output is misalignment. 

In the `rv32emu`, `arr1` and `arr2` are stored in contiguous memory address. First `lw` instruction checks whether the address of `arr1` + 4 is misaligned. Because the start address of `arr1` is aligned, the address of `arr1` + 4 is also aligned. Therefore, first `lw` instruction loads 3 bytes of data of `arr1` and 1 byte of data of `arr2`. However, the start address of `arr2` is the start address of `arr1` + 3, so second `lw`  instruction finds out `arr2` + 4 is misaligned and calls exeception handler without printing any data.

As alternative, you can use `lb` instruction to load a byte of data.

**Comment by maromaSamsa** [comment]
> However, the start address of `arr2` is the start address of `arr1` + 3, so second `lw` instruction finds out `arr2` + 4 is misaligned and calls exeception handler without printing any data.

Thanks for your reply, I think this explanation convince me why the unexpected output doesn't print any character when misaligned occur in `rv32emu`, and I am curious about the source code. 

 > As alternative, you can use `lb` instruction to load a byte of data.

Since I hope I can save the memory by constrain the test data into byte, and also `lw` is more efficiency than `lb` cause I can spent only one instruction time to load 4 byte, I choose to use `lw` if it is possible.

**Comment by qwe661234** [comment]
> Thanks for your reply, I think this explanation convince me why the unexpected output doesn't print any character when misaligned occur in rv32emu, and I am curious about the source code.

You can check the `op_load` function in file `emulate.c`.

**Comment by jserv** [comment]
I probably close this as the issue is not one of emulator flaws.
