### ISSUE TITLE
Use of floating point library functions

### ISSUE THREAD

**Issue by 2011eric** [sysprog21/rv32emu#87]
https://github.com/sysprog21/rv32emu/blob/2b114431865312dcfe8b9f1b4c6d8aeeeb4b5564/src/emulate.c#L18-L27

We've used some library functions in `emulate.c`
But there are also implementations in `calc_fclass()` that provides similar functionality:
https://github.com/sysprog21/rv32emu/blob/2b114431865312dcfe8b9f1b4c6d8aeeeb4b5564/src/soft_float.h#L28-L59

Which one should we stick to?

**Comment by jserv** [comment]
When there are several options to choose from, I like the one that is easier to follow and more direct.

**Comment by jserv** [comment]
> When there are several options to choose from, I like the one that is easier to follow and more direct.

@2011eric, Are you going to refine the code?
